---
title: "mix taglist and plots"
author: "OEB"
date: "February 6, 2018"
output: 
  html_document: 
    number_sections: yes
    toc: yes
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}

suppressPackageStartupMessages( require(oetteR) )
suppressPackageStartupMessages( require(tidyverse) )

```


# Generate Mixed list

```{r}

tab = f_datatable_universal( mtcars )

p = ggplot(mtcars, aes(disp, mpg) ) +
  geom_point()

tag1 = f_html_padding( tab, title = 'tag1')

tag2 = f_html_padding( tab, title = 'tag2') 

p_plotly = plotly::ggplotly(p)

tabplot = tabplot::tableplot( mtcars, plot = F )

mix = list( p_plotly, tag1, p, tabplot, tab) 


```


# Try to identify object

```{r results='asis'}

# objects = tibble( obj = mix ) %>%
#   mutate( class = map(obj, class)
#           , class = map_chr( class, function(x) x[[1]] )
#           #, print_f = map(class, function(x) ifelse( x == 'tabplot',tabplot:::plot.tabplot, print) )
#           # , print_f = map(class, function(x) ifelse( x %in% c('plotly', 'shiny.tag.list', 'datatables')
#           #                                            , htmlwidgets:::knit_print.htmlwidget, print) )
#           , print_f = map(class, function(x) ifelse( x %in% c('plotly')
#                                                      , htmlwidgets:::knit_print.htmlwidget, print) )
#           , exec = walk2(obj, print_f, function(x,y) y(x) )
#           )
# 

list( p_plotly, p_plotly ) %>%
  walk( htmlwidgets:::knit_print.htmlwidget )


```

