

#' @title generates sequence of variable spanning from min to max
#' @description similar to modelr::seq_range but can handle categorical variables
#' @param data_ls data_ls object generated by f_clean_data(), or a named list
#'   list( data = <dataframe>, numericals = < vector with column names of
#'   numerical columns>)
#' @param col_var character vector denoting variable
#' @param n integer number of intermediate data points, Default: 500
#' @return vector
#' @examples
#' data_ls = f_clean_data(mtcars)
#' col_var = 'disp'
#' f_model_seq_range( data_ls, col_var, 10)
#' @rdname f_model_seq_range
#' @export
f_model_seq_range = function( data_ls, col_var, n = 500 ){

  vec = data_ls$data[[col_var]]

  if(col_var %in% data_ls$numericals){
    sequence = seq( min(vec), max(vec), length.out = n)
  }else{
    sequence = levels( vec )
  }

  return(sequence)
}

#' @title generates a data grid based on a formula
#' @description the range of one specified variable is expanded, while all other
#'   variables are set to the most common values. Similar to modelr::data_grid
#'   but it can deal with factors.
#' @param data_ls data_ls object generated by f_clean_data(), or a named list
#'   list( data = <dataframe>, numericals = < vector with column names of
#'   numerical columns>)
#' @param formula formula
#' @return dataframe
#' @examples
#' data_ls = f_clean_data(mtcars)
#' formula = disp~cyl+mpg+hp
#' f_model_data_grid( 'mpg', data_ls, formula,  10 )
#' @rdname f_model_data_grid
#' @export
f_model_data_grid = function( col_var, data_ls, formula, n = 500 ){

  vars         = f_manip_get_variables_from_formula(formula)

  response_var_sym = as.name(col_var)

  if( ! col_var %in% vars ){
    stop('f_model_data_grid supplied variable is not in formula')
  }

  summarized_ls = f_manip_summarize_2_median_and_most_common_factor(data_ls)

  range = f_model_seq_range( data_ls, col_var, n )

  grid = summarized_ls$data %>%
    select( one_of(vars) )%>%
    mutate( !!response_var_sym := list( response_var_sym = range ) ) %>%
    unnest( !!response_var_sym , .drop = F) %>%
    select( one_of(col_var), everything() )

  return(grid)

}

#' @title add predictions to grid (regression models)
#' @description wrapper for modelr::add_predictions
#' @param grid grid containing all variables used for the model
#' @param m model
#' @param var character vector denoting response variable
#' @return grid
#' @examples
#' data_ls = f_clean_data(mtcars)
#' formula = disp~hp+mpg
#' m = lm(formula, data_ls$data)
#' grid = f_model_data_grid(data_ls, formula, 'hp', 10) %>%
#'   f_model_add_predictions_2_grid_regression( m, 'disp')
#' @seealso
#'  \code{\link[modelr]{add_predictions}}
#' @rdname f_model_add_predictions_2_grid_regression
#' @export
#' @importFrom modelr add_predictions
f_model_add_predictions_2_grid_regression = function( grid, m, var){

  grid = grid %>%
    modelr::add_predictions( m, var)

  return(grid)

}

#' @title FUNCTION_TITLE
#' @description FUNCTION_DESCRIPTION
#' @param data_ls PARAM_DESCRIPTION
#' @param m PARAM_DESCRIPTION
#' @param formula PARAM_DESCRIPTION
#' @param ranked_variables PARAM_DESCRIPTION
#' @param col_vector PARAM_DESCRIPTION
#' @param limit PARAM_DESCRIPTION, Default: 10
#' @return OUTPUT_DESCRIPTION
#' @details DETAILS
#' @examples
#' \dontrun{
#' if(interactive()){
#'  #EXAMPLE1
#'  }
#' }
#' @seealso
#'  \code{\link[modelr]{data_grid}}
#' @rdname f_model_plot_variable_dependency_regression
#' @export
#' @importFrom modelr data_grid
f_model_plot_variable_dependency_regression = function( m
                                                       , ranked_variables
                                                       , data = NULL
                                                       , formula
                                                       , data_ls
                                                       , col_vector
                                                       , limit = 10
                                                      ){

  # modelling data might have been filtered therefore we will replace data
  # data_ls

  data_ls$data = as.data.frame(data)

  response_var = f_manip_get_response_variable_from_formula( formula )

  #plot function

  vars_and_col = ranked_variables %>%
    rename( variables = row_names ) %>%
    arrange_( 'rank' ) %>%
    head( limit ) %>%
    left_join( col_vector )

  grid = vars_and_col %>%
    mutate( grid = map( variables
                        , f_model_data_grid
                        , data_ls
                        , formula)
            ,grid = map( grid, f_model_add_predictions_2_grid_regression, m, response_var)
            ) %>%
    unnest(grid, .drop = F) %>%
    mutate( rwn = 1:nrow(.)
            , x = map2(variables, rwn, function(var,rwn,data) data[[var]][rwn], .)
            , x = unlist(x)
            , x = as.numeric(x)
            )

    ggplot( grid, aes_string( 'x', response_var, color = 'variables') ) +
      geom_line( size = 2) +
      facet_wrap(~variables, scales = 'free_x') +
      theme( legend.position = 'None') +
      labs( x = ''
            , y = class(m)[2] ) +
      scale_color_manual( values = vars_and_col$color )


}
